import { CoachingCollection, SocialLink } from '../types';

export const INITIAL_LINKS: SocialLink[] = [
  {
    id: 'link-1',
    url: 'https://x.com/DanKoe/status/1784920448102941',
    platform: 'x',
    title: '10 Frameworks for Scaling High-Ticket Coaching in 2025',
    notes: 'Section 4 on asynchronous client onboarding is gold. Essential for Q2 program redesign.',
    tags: ['#Coaching', '#Frameworks', '#Business'],
    author: 'Dan Koe',
    authorHandle: '@DanKoe',
    authorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAST1RkPEt2mbxwD9uTzff3hYqXP2ZtuviYUau4kI-SOwVqXdKSs0sBPu4CJuw8t3dvD5KKn3dft8hHrVOaVgAkPSok2HXjm0I48YLLULE7s-d5I1DFt7FVBljnP4UPP923TnwSeHCsRe0OPy3FB9fI_gZYLDc9QCvm8XlR27y95rxAh8WQR1aB9N20ngk41id_mYf5giEaP3qymILG4k0SR4vVKIqA9PApO068SJQINbarVOe9OYHj',
    verified: true,
    badge: 'X',
    dateAdded: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    displayTimeAgo: '2 hours ago',
    collectionId: 'col-1',
    originalText: '"The paradox of leverage: Less availability creates higher perceived authority."',
    stats: { reposts: '1.4k', likes: '8.9k', bookmarks: '342' },
    assetFormat: 'framework',
    extractedInsight: 'Asynchronous onboarding creates leverage and positions your time as premium executive consulting.',
  },
  {
    id: 'link-2',
    url: 'https://threads.net/@shane_mac/post/8821932',
    platform: 'threads',
    title: 'Why 90% of Personal Brands Fail in the First 90 Days',
    notes: 'Consistency over novelty. Focus on building micro-audiences that retain trust and value.',
    tags: ['#ThreadsStrategy', '#Branding', '#Marketing'],
    author: 'Shane Mac',
    authorHandle: '@shane_mac',
    authorAvatar: '',
    verified: true,
    badge: 'Threads',
    dateAdded: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    displayTimeAgo: '4 hours ago',
    collectionId: 'col-4',
    originalText: '"The trap is thinking you need 50,000 followers. You only need 100 deeply invested leaders who treat your advice like operating system updates."',
    stats: { reposts: '420', likes: '3.2k', bookmarks: '180' },
    assetFormat: 'breakdown',
    extractedInsight: 'Cultivate 100 micro-tier evangelists rather than broad shallow social reach.',
  },
  {
    id: 'link-3',
    url: 'https://linkedin.com/posts/sarah-jenkins-neuro/89201',
    platform: 'linkedin',
    title: 'The Executive Guide to Sustainable Peak Performance',
    notes: 'Sleep metrics vs cognitive output study. Excellent reference data for executive client debriefs.',
    tags: ['#Health', '#Leadership', '#Productivity'],
    author: 'Dr. Sarah Jenkins',
    authorHandle: 'Cognitive Neuroscientist · LinkedIn',
    verified: true,
    badge: '1st',
    dateAdded: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    displayTimeAgo: 'Yesterday',
    collectionId: 'col-2',
    originalText: 'Deep Sleep Index > 1.5h directly correlates with +34% Decision Velocity in executive founders.',
    stats: { likes: '1.9k', bookmarks: '520' },
    assetFormat: 'framework',
    extractedInsight: 'Circadian phase anchoring stabilizes afternoon decision bandwidth.',
  },
  {
    id: 'link-4',
    url: 'https://facebook.com/groups/growthlab/posts/2910481',
    platform: 'facebook',
    title: 'Community Building Masterclass: 0 to 15k Active Members Case Study',
    notes: 'Weekly live Q&A framework structure with structured 5-minute problem pitches.',
    tags: ['#Community', '#Growth', '#Facebook'],
    author: 'Community Builders',
    authorHandle: 'Private Mastermind · Facebook Group',
    verified: false,
    badge: 'Group',
    dateAdded: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    displayTimeAgo: '3 days ago',
    collectionId: 'col-1',
    originalText: '"The key ritual: Wednesday Peer Hotseats with structured 5-minute problem pitches."',
    stats: { likes: '740', reposts: '89' },
    assetFormat: 'template',
    extractedInsight: 'Implement Wednesday peer hotseats with strict 5-minute timers.',
  },
  {
    id: 'link-5',
    url: 'https://x.com/AlexHormozi/status/1781209384',
    platform: 'x',
    title: 'The Grand Slam Offer Blueprint: Pricing vs Value Equation',
    notes: 'The 4 leverage pillars: Code, Media, Capital, Labor. Use for client audit module.',
    tags: ['#Business', '#Coaching', '#Pricing'],
    author: 'Alex Hormozi',
    authorHandle: '@AlexHormozi',
    authorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC4_R2Woq7_pbiQKV15Q1Bn8BLLBFdkFgRjAE7LFMIAvS7xatEMg7Rdkz_C6idmkw8Lc-79nLy4ahiASbRBngFE2mkngGp00B0eJncFF9QpW3unun6EUku7ZPzSBo_9DQVKYZFTkJUmNUyOAkfwVNO7GX56gPRnBb6yBoYq9xZPO9xmpWjKXXK2ySyWiu9U6CwsDll0A8am3JBs-JjVn8p95-lxF6gk-VE5DU0WUscqI-K5D1T6Tmn8',
    verified: true,
    badge: 'X',
    dateAdded: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    displayTimeAgo: '4 days ago',
    collectionId: 'col-3',
    originalText: '"If you want to charge 10x more, don\'t make the product 10x better. Eliminate 10x of the effort and sacrifice required from the customer."',
    stats: { likes: '9.8k', reposts: '1.4k', bookmarks: '3,410' },
    assetFormat: 'framework',
    extractedInsight: 'Eliminate 10x of customer effort instead of inflating feature checklists.',
  },
  {
    id: 'link-6',
    url: 'https://linkedin.com/posts/tiago-forte-pkms/90123',
    platform: 'linkedin',
    title: 'Building a Second Brain: The Modern Architecture of Personal Knowledge',
    notes: 'CODE method: Capture, Organize, Distill, Express. Essential knowledge system for clients.',
    tags: ['#Productivity', '#Frameworks', '#Systems'],
    author: 'Tiago Forte',
    authorHandle: 'Founder, Forte Labs · LinkedIn',
    verified: true,
    badge: '1st',
    dateAdded: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    displayTimeAgo: '5 days ago',
    collectionId: 'col-2',
    originalText: '"Your mind is for having ideas, not holding them. Build external scaffolding that preserves your best insights."',
    stats: { likes: '3.1k', bookmarks: '890' },
    assetFormat: 'breakdown',
    extractedInsight: 'Organize by actionability (Projects, Areas, Resources, Archives) rather than source topics.',
  },
  {
    id: 'link-7',
    url: 'https://x.com/ShaanVP/status/1782019482',
    platform: 'x',
    title: 'How to Validate a 6-Figure Advisory Service in 7 Days',
    notes: 'The Pre-Sale Validation Loop: Interview 5 target clients before writing a single slide.',
    tags: ['#Coaching', '#Sales', '#Business'],
    author: 'Shaan Puri',
    authorHandle: '@ShaanVP',
    verified: true,
    badge: 'X',
    dateAdded: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    displayTimeAgo: '6 days ago',
    collectionId: 'col-1',
    originalText: '"The fastest path to product-market fit: Ask prospects to pay deposit before you build the curriculum."',
    stats: { likes: '4.2k', reposts: '760', bookmarks: '1.2k' },
    assetFormat: 'framework',
  },
  {
    id: 'link-8',
    url: 'https://threads.net/@justinwelsh/post/991204',
    platform: 'threads',
    title: 'The Solopreneur Operating System: 4 Hours of Deep Focus Daily',
    notes: 'Time-blocking matrix: Morning production, afternoon meetings, zero late-night notifications.',
    tags: ['#Productivity', '#Solopreneur', '#Focus'],
    author: 'Justin Welsh',
    authorHandle: '@justinwelsh',
    verified: true,
    badge: 'Threads',
    dateAdded: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    displayTimeAgo: '1 week ago',
    collectionId: 'col-2',
    originalText: '"You do not need an 80-hour work week. You need 20 hours of ruthless prioritization and non-negotiable focus."',
    stats: { likes: '5.6k', reposts: '890' },
    assetFormat: 'template',
  },
];

export const INITIAL_COLLECTIONS: CoachingCollection[] = [
  {
    id: 'col-1',
    title: 'Sales & Client Acquisition',
    subtitle: 'Direct frameworks, conversation architectures, and high-ticket closing blueprints.',
    tags: ['#Coaching', '#Sales', '#Acquisition'],
    color: 'teal',
    coachSynthesis: 'Focus on links #1 and #7 for conversational positioning and pre-sales offer validation.',
    linkIds: ['link-1', 'link-4', 'link-7'],
    avatarPreviews: [],
    readinessScore: 85,
    updatedAt: '2 hours ago',
    activePillar: true,
  },
  {
    id: 'col-2',
    title: 'Focus & Peak Performance',
    subtitle: 'Energy management, cognitive stamina, and asynchronous execution systems.',
    tags: ['#Productivity', '#Leadership', '#Systems'],
    color: 'blue',
    coachSynthesis: 'Daily deep-work routines, executive sleep optimization, and intentional focus rituals.',
    linkIds: ['link-3', 'link-6', 'link-8'],
    avatarPreviews: [],
    readinessScore: 90,
    updatedAt: 'Yesterday',
    activePillar: false,
  },
  {
    id: 'col-3',
    title: 'Offer Design & Pricing Models',
    subtitle: 'High-ticket value equations, tier structuring, and premium consulting packaging.',
    tags: ['#Pricing', '#Business', '#Offers'],
    color: 'teal',
    coachSynthesis: 'Principles on 10x effort elimination and outcome guarantees.',
    linkIds: ['link-5'],
    avatarPreviews: [],
    readinessScore: 75,
    updatedAt: '4 days ago',
    activePillar: false,
  },
  {
    id: 'col-4',
    title: 'Content Strategy & Audience',
    subtitle: 'High-signal writing, authority positioning, and micro-audience loyalty.',
    tags: ['#Marketing', '#Branding', '#Content'],
    color: 'slate',
    coachSynthesis: 'Writing hooks that attract high-tier founders without algorithmic chasing.',
    linkIds: ['link-2'],
    avatarPreviews: [],
    readinessScore: 80,
    updatedAt: '4 hours ago',
    activePillar: false,
  },
];
